# Generated by Django 6.0.4 on 2026-05-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'verbose_name_plural': 'Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'User Details'},
        ),
    ]
