# Generated by Django 6.0.4 on 2026-05-07 12:00

import django.db.models.deletion
import expense.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=expense.models.expense_receipt_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size_kb', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='expense.expense')),
            ],
            options={
                'db_table': 'expense_receipts',
            },
        ),
    ]
