# Generated by Django 6.0.4 on 2026-05-18 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_expensereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='auto_approve_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Scheduled time for Celery to check/auto-process'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='is_amount_auto_approved',
            field=models.BooleanField(default=False, help_text='True if expense amount was below AUTO_APPROVE_AMOUNT_LIMIT'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approve_or_rejected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when an admin manually approved or rejected', null=True),
        ),
    ]
