# Generated by Django 6.0.4 on 2026-05-19 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_expense_auto_approve_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='actioned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected the expense. NULL for auto approvals.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
