# Generated by Django 6.0.4 on 2026-05-18 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='fcm_sent',
            field=models.BooleanField(default=False, help_text='True if FCM notification was successfully delivered'),
        ),
        migrations.AddField(
            model_name='notification',
            name='fcm_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the FCM push was sent successfully', null=True),
        ),
        migrations.CreateModel(
            name='FcmTokens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('device_type', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fcm Token',
                'db_table': 'fcm_tokens',
            },
        ),
    ]
